spring.application.name=CONVIVIRSMART

server.port=8215

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://contactonovashop4_db_user:Convivir123@cluster0.tee29a7.mongodb.net/CONVIVIRSMART


spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JWT
jwt.secret=c29udml2aXJzbWFydC1zZWNyZXQta2V5LXBhcmEtanNvbi13ZWItdG9rZW5z
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG


spring.mail.host=mail.deltadevsystems.com
spring.mail.port=465

spring.mail.username=contacto@deltadevsystems.com
spring.mail.password=+Deltadev2025


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=*

spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB